### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by NievesBorrero** [pabloleonalcaide/TopMusicException#1]
Hola Pablo!, estaría bien que este método devolviera un String en lugar de un StringBuilder de esta manera:

return ten.toString

Un saludo!

https://github.com/pabloleonalcaide/TopMusicException/blob/master/topMusicException/TopMusic.java#L46

**Comment by pabloleonalcaide** [comment]
Muchas gracias!  lo apunto para modificarlo

**Comment by pabloleonalcaide** [comment]
Ya está modificado, gracias!
